from client2 import get_errors
ID = 'SOql4uavXyMdC9BTYktZDz152sPIhQLm6ucxoy2ujxmqb8o7E1'
vector = [4.898712714478583, -1.2439799891883509e-12, -2.374161028538222e-13, 8.145994377709371e-11, -1.7117817833960421e-10, -1.8366976965696096e-15, 6.35513405133212e-16, 2.3462516835537143e-05, -2.0472100298772093e-06, -1.4876080539133759e-08, 9.572911174164225e-10]# : [113206875020.648, 169702969009.363]
# [113206875020.648, 169702969009.363]

# vector = [2.2182692939816406, -8.406005551968384e-13, -1.6139888992223963e-13, 2.4077482807861072e-11, -1.615490567876983e-10, -1.5171321998639492e-15, 6.209270009663088e-16, 2.4143331126273833e-05, -1.7795178512790162e-06, -1.729484375828036e-08, 8.842286162578946e-10]
# [85636179114.89194, 106148556728.45224]

assert len(vector) == 11
print(get_errors(ID, vector))
